---
title: "spotify"
author: "Yu-Xiang, Lin"
date: "2019/12/17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load packages 
```{r}
library(tidyverse)
library(httr)
library(rvest)
library(jsonlite)
library(tidytext)
```
#access to spotify api
```{r}
client_id <- "19185c77d6db47e1b53089a2b33bd82d"
client_secret <- "3af2ba20fd47463aba7ad3432dac1f90"
response = POST(
  'https://accounts.spotify.com/api/token',
  accept_json(),
  authenticate(client_id, client_secret),
  body = list(grant_type = 'client_credentials'),
  encode = 'form',
  verbose()
)
token = content(response)$access_token
authorization.header = paste0("Bearer ", token)
```
# get all album id
```{r}
id_df <- data_frame()
rco <- "2HqNckz4bPVT37fWkhugTZ"
for (ii in 1){
url1 <- paste0("https://api.spotify.com/v1/artists/",rco,"/albums?&limit=50")
result <- fromJSON(content(GET(url1,config = add_headers(authorization = authorization.header)),"text"))
total <- result$total
message(total)
id_df <- data_frame()
for (i in 0:floor(total/50)){
  url2 <- paste0("https://api.spotify.com/v1/artists/",rco,"/albums?&offset=",50*i,"&limit=50")
  result <- fromJSON(content(GET(url2,config = add_headers(authorization = authorization.header)),"text"))
  df <- data_frame(result$items$id)
  id_df <- bind_rows(df,id_df)
}
}
```
#get all tracks from album
```{r}
res_df <- data_frame()
for (i in 938:nrow(id_df)){
  #Sys.sleep(sample(5))
  url <- paste0("https://api.spotify.com/v1/albums/",id_df[i,1],"/tracks?limit=47")
  result<- fromJSON(content(GET(url,config = add_headers(authorization = authorization.header)),"text"))
  message("first message ",result$total,"and",i)
  total <- result$total
  if(total%%47!=0){
    for ( ii in 0:floor((total/47))){
      url2 <- paste0("https://api.spotify.com/v1/albums/",id_df[i,1],"/tracks?limit=47&offset=",47*ii)
      result2<- fromJSON(content(GET(url2,config = add_headers(authorization = authorization.header)),"text"))
      message("second message ",result$total,"and",i)
      
      df <- data_frame(result2$items$artists,result2$items$name)
      res_df <- bind_rows(df,res_df)
    }
  }else for ( ii in 0:floor((total/50))){
    url2 <- paste0("https://api.spotify.com/v1/albums/",id_df[i,1],"/tracks?limit=50&offset=",50*ii)
    result2<- fromJSON(content(GET(url2,config = add_headers(authorization = authorization.header)),"text"))
    message("second message ",result$total,"and",i)
  }
  Sys.sleep(0.3)
}
```
#確認最多有幾個artist
```{r}
res_df$artist <- 0
for (i in 1:nrow(res_df)){
  name<- paste(res_df$`result2$items$artists`[[i]]$name,collapse="_")
  res_df$artist[i] <- name
}
res_df2 <- res_df[,-1]
res_df2 <- distinct(res_df2)
res_df2 <- separate(res_df2,artist,into=
                      c("artist1","artist2","artist3","artist4","artist5",
                        "artist6","artist7","artist8","artist9","artist10",
                        "artist11","artist12","artist13","artist14","artist15",
                        "artist16","artist17","artist18","artist19","artist20",
                        "artist21","artist22","artist23","artist24","artist25",
                        "artist26","artist27","artist28","artist29","artist30",
                        "artist31","artist32","artist33","artist34","artist35",
                        "artist36","artist37","artist38","artist39","artist40",
                        "artist41","artist42","artist43","artist44","artist45",
                        "artist46","artist47","artist48","artist49","artist50"),sep="_")
```
#把只有一個參與者的曲目剔除
```{r}
res_df2 <- res_df2%>%
  filter(!is.na(res_df2$artist2)==T)
artist_df <- res_df2%>%distinct()%>%select(-`result2$items$name`)
```
#篩選只有該樂團的obs
```{r}

#artist_var <- c("artist1","artist2","artist3","artist4","artist5",
 #               "artist6","artist7","artist8","artist9","artist10",
  #              "artist11","artist12","artist13","artist14","artist15",
   #             "artist16","artist17","artist18","artist19","artist20",
    #            "artist21","artist22","artist23","artist24","artist25",
     #           "artist26","artist27","artist28","artist29","artist30",
      #          "artist31","artist32","artist33","artist34","artist35",
       #         "artist36","artist37","artist38","artist39","artist40",
        #        "artist41","artist42","artist43","artist44","artist45",
         #       "artist46","artist47","artist48","artist49","artist50")
# 創造包含所有column的變項
artist_df$artist_var <- paste0(
  artist_df$artist1,artist_df$artist2,artist_df$artist3,artist_df$artist4,
  artist_df$artist5,artist_df$artist6,artist_df$artist7,artist_df$artist8,
  artist_df$artist9,artist_df$artist10,artist_df$artist11,artist_df$artist12,
  artist_df$artist13,artist_df$artist14,artist_df$artist15,artist_df$artist16,
  artist_df$artist17,artist_df$artist18,artist_df$artist19,artist_df$artist20,
  artist_df$artist21,artist_df$artist22,artist_df$artist23,artist_df$artist24,
  artist_df$artist25,artist_df$artist26,artist_df$artist27,artist_df$artist28,
  artist_df$artist29,artist_df$artist30,artist_df$artist31,artist_df$artist32,
  artist_df$artist33,artist_df$artist34,artist_df$artist35,artist_df$artist36,
  artist_df$artist37,artist_df$artist38,artist_df$artist39,artist_df$artist40,
  artist_df$artist41,artist_df$artist42,artist_df$artist43,artist_df$artist44,
  artist_df$artist45,artist_df$artist46,artist_df$artist47,artist_df$artist48,
  artist_df$artist49,artist_df$artist50,sep=" ")%>%
  str_replace_all("NA","")
artist_df_clear <- artist_df%>%filter(str_detect(artist_var,
                     "(?i)Royal Concertgebouw Orchestra")==1)%>%select(-artist_var)
saveRDS(artist_df_clear,file="/Users/linyuxiang/R/Spotify/artist wide dataframe/rco_artist_df.rds")
```
#create network form data
```{r}
df2 <- data.frame()
for (i in 1:nrow(artist_df_clear)){
df <- as.data.frame(t(combn(artist_df_clear[i,],2)))%>%filter(is.na(V2)!=1)
df2 <- bind_rows(df,df2)
message(i)
}
df2 <- unique(df2[,c("V1","V2")])%>%
  filter(str_detect(V1,"/")==0)%>%
  filter(str_detect(V2,"/")==0)

mat <- as.matrix(df2)
mat2 <- matrix(unlist(mat),nrow=nrow(mat),byrow=F)
saveRDS(mat2,file="/Users/linyuxiang/R/Spotify/before network matrix/rco_mat.rds")

```



